create table if not exists tg_group_config (
  id bigint primary key auto_increment,
  group_id bigint not null,
  group_name varchar(255),
  language varchar(16) not null,
  enabled tinyint(1) not null default 1,
  sort_weight int not null default 0,
  trust_level int not null default 0,
  allowed_symbols_json json,
  push_enabled tinyint(1) not null default 1,
  created_at datetime not null default current_timestamp,
  updated_at datetime not null default current_timestamp on update current_timestamp,
  unique key uk_tg_group_config_group_id (group_id),
  key idx_tg_group_config_enabled (enabled)
) engine=InnoDB default charset=utf8mb4;

create table if not exists tg_raw_message (
  id bigint primary key auto_increment,
  update_id bigint not null,
  group_id bigint not null,
  group_name varchar(255),
  language varchar(16) not null,
  message_id bigint not null,
  sender_id bigint,
  sender_name varchar(255),
  sender_first_name varchar(255),
  sender_last_name varchar(255),
  sender_username varchar(255),
  sender_is_admin tinyint(1) not null default 0,
  sent_at datetime,
  text text,
  normalized_text text,
  entities_json json,
  reply_to_message_id bigint,
  reply_to_text text,
  forward_date datetime,
  forward_from_id bigint,
  forward_from_username varchar(255),
  forward_from_chat_id bigint,
  has_link tinyint(1) not null default 0,
  has_media tinyint(1) not null default 0,
  ingest_status varchar(32) not null,
  retry_count int not null default 0,
  next_retry_at datetime,
  last_error text,
  processing_started_at datetime,
  created_at datetime not null default current_timestamp,
  updated_at datetime not null default current_timestamp on update current_timestamp,
  unique key uk_tg_raw_group_message (group_id, message_id),
  unique key uk_tg_raw_update_id (update_id),
  key idx_tg_raw_status_retry (ingest_status, next_retry_at),
  key idx_tg_raw_group_sent (group_id, sent_at),
  key idx_tg_raw_language_sent (language, sent_at)
) engine=InnoDB default charset=utf8mb4;

create table if not exists tg_push_decision_log (
  id bigint primary key auto_increment,
  raw_message_id bigint not null,
  language varchar(16),
  symbol varchar(32),
  event_type varchar(32),
  sentiment varchar(32),
  topic varchar(128),
  decision varchar(16) not null,
  decision_reason varchar(128),
  dedupe_key varchar(128),
  rate_limited tinyint(1) not null default 0,
  final_content varchar(255),
  created_at datetime not null default current_timestamp,
  key idx_tg_decision_raw_message (raw_message_id),
  key idx_tg_decision_decision_created (decision, created_at),
  key idx_tg_decision_lang_symbol_created (language, symbol, created_at)
) engine=InnoDB default charset=utf8mb4;

create table if not exists danmaku_push_log (
  id bigint primary key auto_increment,
  raw_message_id bigint not null,
  decision_id bigint,
  symbol varchar(32),
  language varchar(16),
  topic varchar(128),
  push_content varchar(255),
  push_status varchar(32),
  response_body text,
  request_id varchar(64),
  pushed_at datetime,
  key idx_danmaku_push_raw_message (raw_message_id),
  key idx_danmaku_push_decision (decision_id),
  key idx_danmaku_push_symbol_pushed (symbol, pushed_at)
) engine=InnoDB default charset=utf8mb4;
